global:
  scrape_interval: 15s

scrape_configs:
  - job_name: "otelshield"
    static_configs:
      - targets: ["otelshield:9464"]
  - job_name: "otelshield-controlplane"
    metrics_path: /metrics
    static_configs:
      - targets: ["controlplane:8081"]
